"""empty message

Revision ID: 36af33ceef0a
Revises: f4fe7d7674aa
Create Date: 2019-03-28 21:58:36.464567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36af33ceef0a'
down_revision = 'f4fe7d7674aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wheel')
    # ### end Alembic commands ###
