"""empty message

Revision ID: 97f7d12aea65
Revises: 36af33ceef0a
Create Date: 2019-03-28 22:41:58.683616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f7d12aea65'
down_revision = '36af33ceef0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheel_re',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img1', sa.String(length=128), nullable=True),
    sa.Column('img2', sa.String(length=128), nullable=True),
    sa.Column('img3', sa.String(length=128), nullable=True),
    sa.Column('img4', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wheel_re')
    # ### end Alembic commands ###
